---
title: "Title"
author: ""
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: spacelab
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
#if there's anymore libraries we might need, include them here :)
library(tidyverse)
library(RColorBrewer)
library(paletteer)
library(janitor)
library(here)
library(naniar)
```

```{r, comment=NA, message=FALSE, warning=FALSE}
plant_sizes <- read_csv(here("Plant+Pollinators Data", "Flower size measurements.csv")) %>% janitor::clean_names()
plant_pollinators <- read_csv(here("Plant+Pollinators Data", "Pollinator and flower color.csv")) %>% janitor::clean_names()
```

```{r, comment=NA, warning=FALSE}
plants_merge <- merge(plant_sizes, plant_pollinators, by="species")
plants <- plants_merge %>%
  select(-mean_corolla_length_cm, -standard_deviation_corolla_length_cm, -mean_corolla_width_cm, -standard_deviation_corolla_width_cm, -length_width_ratio) %>%
  rename(color_source="source", pollinator_source="source_1") %>%
  filter(herbarium_accession_sheet!="NA" & flower_number!="NA" & corolla_length_cm!="NA" & corolla_width_throat_cm!="NA" & color!="NA" & pollinator!="NA") %>%
  mutate_all(funs(str_replace(., " or", ", "))) %>%
  mutate_all(funs(str_replace(., " and", ", "))) %>%
  mutate_all(funs(str_replace(., "/", ", "))) %>%
  mutate_all(funs(str_replace(., " to", ", "))) %>%
  separate(color, into=c("color_opt_1", "color_opt_2", "color_opt_3", "color_opt_4"), sep=", ") %>%
  mutate_all(funs(str_replace(., " primary,", ", "))) %>%
  mutate_all(funs(str_replace(., " secondary", ""))) %>%
  mutate_all(funs(str_replace(., "bees", "bee"))) %>%
  mutate_all(funs(str_replace(., "butterflies", "butterfly"))) %>%
  mutate_all(funs(str_replace(., "beeflies", "bee-fly"))) %>%
  mutate_all(funs(str_replace(., "beefly", "bee-fly"))) %>%
  na_if("autogamous") %>%
  separate(pollinator, into=c("pollinator_1", "pollinator_2", "pollinator_3"), sep=", ")
plants
```