---
title: "Title"
author: ""
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: spacelab
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
#if there's anymore libraries we might need, include them here :)
library(tidyverse)
library(RColorBrewer)
library(paletteer)
library(janitor)
library(here)
library(naniar)
```

```{r}
plants <- read_csv(here("plantInfo-clean-new.csv")) %>%
  janitor::clean_names()
plants
```

```{r}
plants %>%
  separate(alternate_name, into = c("alt_name_1", "alt_name_2", "alt_name_3"), sep = ",") %>%
  separate(space_instructions, into = c("delete", "space"), sep = ":") %>%
  separate(space, into = c("min_space_apart", "max_space_apart"), sep = "-") %>%
  separate(min_space_apart, into = c("delete2", "min_space_apart", "unit_of_mzr_min"), sep = " ") %>%
  separate(max_space_apart, into = c("delete4", "max_space_apart", "unit_of_mzr_max"), sep = " ") %>%
  separate(harvest_instructions, into = c("delete5", "delete6", "time", "unit_of_time"), sep = " ") %>%
  separate(unit_of_time, into = c("unit_of_time", "delete7"), sep = " ") %>%
  separate(time, into = c("min_harvest_time", "max_harvest_time"), sep = "-") %>%
  separate(compatible_plants, into = c("delete9", "compatible_with"), sep = ":") %>%
  separate(avoid_instructions, into = c("delete10", "avoid_growing_near"), sep = ":") %>%
  separate(culinary_hints, into = c("culinary_hints_1", "culinary_hints_2", "culinary_hints_3"), sep = "/") %>%
  separate(culinary_preservation, into = c("cul_pres_1", "cul_pres_2"), sep = "/") %>%
  separate(sow_instructions, into = c("where_to_grow", "sow_step_1", "sow_step_2", "sow_step_3"), sep = "~") %>%
  separate(where_to_grow, into = c("where_to_grow", "delete3"), sep = ",") %>%
  select(-"delete", -"delete2", -"delete3", -"delete4", -"delete5", -"delete6", -"delete7", -"delete9", -"delete10")
```

